/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProNasRouteImport } from './routes/pro-nas'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as PoslugyIndexRouteImport } from './routes/poslugy.index'
import { Route as PoslugySlugRouteImport } from './routes/poslugy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNasRoute = ProNasRouteImport.update({
  id: '/pro-nas',
  path: '/pro-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyIndexRoute = PoslugyIndexRouteImport.update({
  id: '/poslugy/',
  path: '/poslugy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugySlugRoute = PoslugySlugRouteImport.update({
  id: '/poslugy/$slug',
  path: '/poslugy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro-nas': typeof ProNasRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy/': typeof PoslugyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro-nas': typeof ProNasRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy': typeof PoslugyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro-nas': typeof ProNasRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy/': typeof PoslugyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pro-nas' | '/api/contact' | '/poslugy/$slug' | '/poslugy/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pro-nas' | '/api/contact' | '/poslugy/$slug' | '/poslugy'
  id:
    | '__root__'
    | '/'
    | '/pro-nas'
    | '/api/contact'
    | '/poslugy/$slug'
    | '/poslugy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProNasRoute: typeof ProNasRoute
  ApiContactRoute: typeof ApiContactRoute
  PoslugySlugRoute: typeof PoslugySlugRoute
  PoslugyIndexRoute: typeof PoslugyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-nas': {
      id: '/pro-nas'
      path: '/pro-nas'
      fullPath: '/pro-nas'
      preLoaderRoute: typeof ProNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/': {
      id: '/poslugy/'
      path: '/poslugy'
      fullPath: '/poslugy/'
      preLoaderRoute: typeof PoslugyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/$slug': {
      id: '/poslugy/$slug'
      path: '/poslugy/$slug'
      fullPath: '/poslugy/$slug'
      preLoaderRoute: typeof PoslugySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProNasRoute: ProNasRoute,
  ApiContactRoute: ApiContactRoute,
  PoslugySlugRoute: PoslugySlugRoute,
  PoslugyIndexRoute: PoslugyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
