/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ProNasRouteImport } from './routes/pro-nas'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as PoslugyIndexRouteImport } from './routes/poslugy.index'
import { Route as PoslugySlugRouteImport } from './routes/poslugy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNasRoute = ProNasRouteImport.update({
  id: '/pro-nas',
  path: '/pro-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyIndexRoute = PoslugyIndexRouteImport.update({
  id: '/poslugy/',
  path: '/poslugy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugySlugRoute = PoslugySlugRouteImport.update({
  id: '/poslugy/$slug',
  path: '/poslugy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro-nas': typeof ProNasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy/': typeof PoslugyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro-nas': typeof ProNasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy': typeof PoslugyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro-nas': typeof ProNasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/poslugy/$slug': typeof PoslugySlugRoute
  '/poslugy/': typeof PoslugyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/pro-nas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/poslugy/$slug'
    | '/poslugy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/pro-nas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/poslugy/$slug'
    | '/poslugy'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/pro-nas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/poslugy/$slug'
    | '/poslugy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProNasRoute: typeof ProNasRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  PoslugySlugRoute: typeof PoslugySlugRoute
  PoslugyIndexRoute: typeof PoslugyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-nas': {
      id: '/pro-nas'
      path: '/pro-nas'
      fullPath: '/pro-nas'
      preLoaderRoute: typeof ProNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/': {
      id: '/poslugy/'
      path: '/poslugy'
      fullPath: '/poslugy/'
      preLoaderRoute: typeof PoslugyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/$slug': {
      id: '/poslugy/$slug'
      path: '/poslugy/$slug'
      fullPath: '/poslugy/$slug'
      preLoaderRoute: typeof PoslugySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProNasRoute: ProNasRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  PoslugySlugRoute: PoslugySlugRoute,
  PoslugyIndexRoute: PoslugyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
